name: Update Recent Activity Stats

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Recent Activity Stats
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.README_UPDATE_TOKEN }}
          COMMIT_MESSAGE: "Updated recent activity dev metrics"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
